stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: "1204"
      registry: index.docker.io
timeout: 60
notification:
  recipients:
  - recipient: '#EXP'
    notifier: c-qkqp8:n-g96zn
  condition:
  - Success
  - Changed
  - Failed
